/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        'sans': ['Inter', 'system-ui', 'sans-serif'],
        'heading': ['Poppins', 'system-ui', 'sans-serif'],
      },
      colors: {
        brand: {
          DEFAULT: 'var(--brand-primary)',
          hover: 'var(--brand-hover)',
          light: 'var(--brand-light)',
        },
        primary: {
          50: '#e8fdf2',
          100: '#c6f9dc',
          200: '#91f3bd',
          300: '#4de896',
          400: '#1DC66C',
          500: '#17A858',
          600: '#0d8a45',
          700: '#0a6b37',
          800: '#08562d',
          900: '#064e3b',
        },
        muted: '#A0A0A0',
        'surface': '#2C2C2C',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'bounce-gentle': 'bounceGentle 2s infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        bounceGentle: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-5px)' },
        }
      }
    },
  },
  plugins: [
    require('daisyui'),
  ],
  daisyui: {
    themes: [
      {
        dark: {
          "primary": "#1DC66C",
          "primary-focus": "#17A858",
          "primary-content": "#ffffff",
          "secondary": "#3b82f6",
          "secondary-focus": "#2563eb",
          "secondary-content": "#ffffff",
          "accent": "#f59e0b",
          "accent-focus": "#d97706",
          "accent-content": "#ffffff",
          "neutral": "#1A1A1A",
          "neutral-focus": "#0A0B0E",
          "neutral-content": "#f9fafb",
          "base-100": "#0A0B0E",
          "base-200": "#2C2C2C",
          "base-300": "#333333",
          "base-content": "#ffffff",
          "info": "#3b82f6",
          "success": "#1DC66C",
          "warning": "#f59e0b",
          "error": "#ef4444",
          "--rounded-box": "0.5rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1.9rem",
          "--animation-btn": "0.25s",
          "--animation-input": "0.2s",
          "--btn-text-case": "normal",
          "--btn-focus-scale": "0.95",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "0.5rem",
        },
        light: {
          // ── Emerald Ledger Light Theme ──
          "primary": "#059669",
          "primary-focus": "#059669",
          "primary-content": "#ffffff",
          "secondary": "#ecfdf5",
          "secondary-focus": "#d1fae5",
          "secondary-content": "#065f46",
          "accent": "#f59e0b",
          "accent-focus": "#d97706",
          "accent-content": "#ffffff",
          "neutral": "#eef7f3",
          "neutral-focus": "#d6ede0",
          "neutral-content": "#064e3b",
          "base-100": "#f9f9f7",
          "base-200": "#f4f4f1",
          "base-300": "#e8e8e3",
          "base-content": "#022c22",
          "info": "#3b82f6",
          "success": "#10b981",
          "warning": "#f59e0b",
          "error": "#ef4444",
          "--rounded-box": "1rem",
          "--rounded-btn": "0.75rem",
          "--rounded-badge": "1.9rem",
          "--animation-btn": "0.25s",
          "--animation-input": "0.2s",
          "--btn-text-case": "none",
          "--btn-focus-scale": "0.95",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "0.75rem",
        },
      },
    ],
    darkTheme: "dark",
    base: true,
    styled: true,
    utils: true,
    prefix: "",
    logs: true,
    themeRoot: ":root",
  },
}

